package Tester;
import org.testng.Assert;
import org.testng.annotations.Test;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */



public class LibraryTest {
  
	@Test
	public void test1() {
		Assert.assertTrue(true);
	}
	@Test
	public void test2() {
		Assert.assertTrue(false);
	}
	@Test
	public void test3() {
		Assert.assertTrue(false);
	}
}
